/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#444748",
        "on-primary-fixed": "#1a1c1c",
        "secondary-container": "#474746",
        "surface-container-low": "#1b1b1b",
        "primary-container": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "on-surface-variant": "#c4c7c8",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary": "#313030",
        "on-secondary-fixed": "#1c1b1b",
        "primary-fixed-dim": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "on-surface": "#e2e2e2",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary": "#c8c6c5",
        "on-background": "#e2e2e2",
        "background": "#131313",
        "error-container": "#93000a",
        "surface-container-highest": "#353535",
        "on-primary-container": "#636565",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "secondary-fixed": "#e5e2e1",
        "surface-variant": "#353535",
        "primary": "#ffffff",
        "inverse-surface": "#e2e2e2",
        "error": "#ffb4ab",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#1f1f1f",
        "on-tertiary-container": "#636565",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "surface": "#131313",
        "outline": "#8e9192",
        "on-tertiary": "#2f3131",
        "primary-fixed": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#393939",
        "tertiary-container": "#e2e2e2",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#454747",
        "on-secondary-container": "#b7b5b4",
        "surface-tint": "#c6c6c7",
        "on-primary": "#2f3131",
        "inverse-primary": "#5d5f5f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "20px",
        gutter: "24px",
        "section-gap": "120px",
        "container-max": "1200px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg-mobile": ["Poppins", "sans-serif"],
        "display-lg": ["Poppins", "sans-serif"],
        "code-label": ["'JetBrains Mono'", "monospace"],
        "headline-md": ["Poppins", "sans-serif"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "body-sm": ["Poppins", "sans-serif"],
        "body-lg": ["Poppins", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "code-label": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
